apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-with-all-certs-sept17-app
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/test-with-all-certs-sept17/overlays/development
    repoURL: https://github.com/jdubrick-ai/test-with-all-certs-sept17-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
