---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-with-all-certs-sept17
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-with-all-certs-sept17 
  name: test-with-all-certs-sept17
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi